"""from_filename field

Revision ID: 4b23f1912e9c
Revises: 420ea7aa0f8f
Create Date: 2024-06-16 16:30:16.015761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b23f1912e9c'
down_revision: Union[str, None] = '420ea7aa0f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copyright_video_parts', sa.Column('from_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('copyright_video_parts', 'from_filename')
    # ### end Alembic commands ###
